FROM python:3.8

RUN useradd -m compfest17

WORKDIR /opt/peramal

COPY ./requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PRODUCTION=true

RUN chown -R compfest17:compfest17 /opt/peramal

USER compfest17

EXPOSE 1234

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver --insecure 0.0.0.0:1234"]